### ISSUE TITLE
Review back button navigation 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#295]
## The Issue
Most back button navigation actions return you to the welcome screen. In many cases, a user will want to navigate back one level. One example is: Go into Trending, go into a claim and click back - you'd expect it to go back to Trending. 

## System Configuration
- Device:
- Android version:

## DOD

- [ ] Identify the solution this sprint

**Comment by ceoger** [comment]
On the settings page, there is an arrow for back and hence the "swipe to right " does now work, however, when i click on the  arrow back, it does not take me to the menu or my last activity,  but to a video i was playing, so even if i am in "My LBRY" and i get to the settings page and click on the back arrow, it takes me to a video i was watching earlier instead of my my last location/activity

**Comment by tzarebczan** [comment]
This is an annoyance / UX issue throughout the app. Back button takes you back to home usually, and not the page you'd expect.
