### ISSUE TITLE
Thumbnail blank on downloaded content

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#397]
## The Issue
When revisiting a claim that has been downloaded, the thumbnail tile is blank/black. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
It happens on all claims that were viewed. It looks like it goes back to a state where the video is starting instead of showing the thumb.

**Comment by tzarebczan** [comment]
![screenshot_20190122-085827](https://user-images.githubusercontent.com/8120721/51540224-eb302380-1e23-11e9-8af1-d567329ef2bc.jpg)

**Comment by akinwale** [comment]
Ok, this happens because the media player is displayed over the thumbnail. You will notice that in cases where it takes the media player a few moments to display, the thumbnail will be displayed first.

I remember I tried to display the thumbnail using the media player itself in the past, but it didn't scale the images properly. I'll try this again to see if it that's changed. Otherwise, I'm not quite sure what else we can do here.

**Comment by tzarebczan** [comment]
Clearing this up - the view shown when going to a file page is the 0 second still, which may be blank often. Think we should show the thumb, unless they autoplay (coming later with space management)

**Comment by akinwale** [comment]
Fixed.
