### ISSUE TITLE
Rework show page for videos

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#430]
1. It's weird that the send a tip button is fixed when this button is fixed with the video when scrolling. It's less important that the title and publisher. It should either be inline with subscribe or below if it cannot fit. It may make sense to move both "send a tip" and "stop download" / "delete" below the channel name and subscribe button.
2. The stop download button is kind of weird and missing an icon (use a stop icon).
3. The description can be truncated/shortened.

**Comment by akinwale** [comment]
1. Send tip button was moved. Fixed in https://github.com/lbryio/lbry-android/pull/512/commits/02826196433dcdd7d098b7b9dbe26b8693a24db3
2. Added in https://github.com/lbryio/lbry-android/pull/518/commits/2fce9580920d681281537bc480dab5fbc365d8e7
3. Description is now collapsed by default and can be expanded.
