### ISSUE TITLE
Describe subscriptions rework

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#475]
This is one of the weakest areas of the app and it should be one of the best and most important (one of our primary use cases is switching over fans of a certain creator to our app).

We should do a top-to-bottom reconsideration of this area and how it should work.

**Comment by toktoakhil** [comment]
Feature request
On Subcriptions tab please add a top ribbon to show the subscribed channels which can be scrolled right and left. Because if someone has subscribed to a large number of channels will be difficult to find individual channels they subscribed if the subscribed channels have not posted for a while.

**Comment by kauffj** [comment]
https://docs.google.com/document/d/1ke81auNPYy1IlAL2nkL-Xh2DQykXZC262Spc6U5rblg/edit @seanyesmunt @akinwale
