### ISSUE TITLE
Look into publishing LBRY Android to Fdroid

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-android#514]
## The Issue
LBRY Android should be listed on fdroid - had another user request for this. 
https://f-droid.org/en/

## LBC Bounty

If you want to solve this issue, see [this comment](https://github.com/lbryio/lbry-android/issues/514#issuecomment-542130756). We are offering a 50,000 LBC bounty for someone to make this app available via FDroid.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
This was moved to an internal issue and I believe the plan is to do so after this initial beta.

**Comment by kauffj** [comment]
What's involved in doing this? If it's easy (and stays current with little/no work), I'm fine with making it available now.

**Comment by tzarebczan** [comment]
I'll take a look into this. Hopefully it can be automated.

**Comment by tzarebczan** [comment]
Looks like it requires forking their repo, setting up a build process, and adding metadata: https://f-droid.org/en/docs/FAQ_-_App_Developers/#how-do-i-get-my-app-included / https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/

I can take a shot at this sometime unless @akinwale wants to.

**Comment by goldenapple3** [comment]
So, is anyone working on this? You do know that the kind of user who doesn't like YouTube also doesn't like relying on Google Play, right? :P
As far as I know, F-Droid does support tools like React Native, Kivy and Buildozer, so as long as you don't depend on proprietary blobs/libraries, the process shouldn't be that difficult.

**Comment by akinwale** [comment]
@goldenapple3 We're looking at creating a bounty for this if any community member wants to tackle this.

**Comment by kauffj** [comment]
@akinwale could you either edit the parent ticket or reply in thread with what challenges make this non-trivial? I believe you had shared this info in chat previously

**Comment by kauffj** [comment]
@akinwale this is marked in progress just to update the original ticket with specifics about what actually needs to happen

**Comment by akinwale** [comment]
Following https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/, these are the steps that need to be taken in order to get the Android app submitted to F-Droid.
* Fork F-Droid
* Create a package and edit the metadata yaml file.
* Fork the `lbry-android` repository and remove references to Firebase. This includes no-oping the methods in `io.lbry.browser.reactmodules.FirebaseModule` (the easiest/quickest way that doesn't break the React Native code) and removing the `google-services.json` file.
* Build the package with `fdroid build`. Some extra steps may be required to get this working with buildozer, considering the way our build is set up. This may need some more exploration.
* Submit a PR to F-Droid.

**Comment by jsigwart** [comment]
just got another request for this again: https://twitter.com/KapPustolov/status/1205680367518261250

**Comment by Adam-Stambaugh** [comment]
An alternative would be to create a F-Droid repository.

**Comment by kauffj** [comment]
@Adam-Stambaugh we would love it if you or someone one else could maintain a fork/build that was F-Droid compatible and LBRY would fund via LBC. Otherwise we want to do this but aren't sure when we'll have the resources.

**Comment by lbrunkho** [comment]
I would really appreciate lbry being free of google play dependencies! +1 for f-droid

**Comment by kauffj** [comment]
Edited OP to mention we are offering 50k LBC bounty for someone who can complete these steps: https://github.com/lbryio/lbry-android/issues/514#issuecomment-542130756

**Comment by Coolguy3289** [comment]
I will look into this

**Comment by Adam-Stambaugh** [comment]
@kauffj What I was proposing is a simpler solution, but it wouldn't satisfy people that want it completely FOSS. F-Droid allows for more than just the default repository. I was just talking about taking the apk, that can already be downloaded on the LBRY site, and hosting that on a separate repository. That way we can get automatic updates. Like I mentioned, though, that would not satisfy people that want the apk to be completely FOSS in the first place.

**Comment by kcseb** [comment]
@Coolguy3289 and I are in a thread with FDroid maintainers trying to work out the best way to actually maintain the functionality of the app completely (or close enough...) while also scrapping `play-services` / `google-services` to get the LBRY app suitable for their (FDroid) acceptance criteria.

Will keep this thread updated with information as we get it!

**Comment by kauffj** [comment]
@kcseb @Adam-Stambaugh @Coolguy3289 at the moment our thoughts are:

- lbry-android (and related projects) is FOSS, so practically any design or required modifications should be possible, regardless of approach.
- We do not have the bandwidth to create or maintain this ourselves.
- We are not active enough users of FDroid to have a strong opinion on approach/design or to understand precisely what other FDroid users want.
- We would like the FDroid community to have a way to run LBRY that meets their satisfaction and we'd like to support that via discussion or LBC as possible. 
- We'd prefer that people work together rather than race against each other. If multiple people want to work on this, can you corroborate? If not, there's plenty of other work to be done.

**Comment by trymeouteh** [comment]
This is what keeping me form downloading the app. I do not like Google, hense I do not use the Google Play Store. Please get this on F-Droid and keep it updated on F-Droid for the privacy minded Android users.

**Comment by Coolguy3289** [comment]
There are some developments on this front in the F-Droid repo. Progress is being made @trymeouteh

**Comment by edwargix** [comment]
> There are some developments on this front in the F-Droid repo. Progress is being made @trymeouteh

How are those developments?  I'm going to give a swing at this.

**Comment by Coolguy3289** [comment]
@edwargix The following is the active merge request on F-Droid, feel free to pitch in here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6610#note_338212351

**Comment by tzarebczan** [comment]
This was completed in https://github.com/lbryio/lbry-android/pull/874
