### ISSUE TITLE
Add download button for playable media

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry-android#532]
With the implementation of range requests, a download button should be added for users who want to download the media to their device.

**Comment by tzarebczan** [comment]
This was removed since it caused the video to reload when the download completed. We had a similar problem implementing this on lbry-desktop. 

Reopening:
- [ ] add save button on file pages
- [ ] add settings option for save_files param in
- [ ] fix the issue where video reloads when download completes

**Comment by harshgandhi** [comment]
Hi. Came here to say this feature is very important for people in places with Poor internet connection. If this feature is made available, I'll help in testing.
