### ISSUE TITLE
Dark/night mode 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#636]
A few users recently requested dark / night mode for the Android app.

**Comment by mohatagarvit** [comment]
Although I'm new to this, but I'll like to claim this for Hacktoberfest!

**Comment by mohatagarvit** [comment]
I'm trying to run this project. But I am facing an error when I run `./build.sh`.
![Screenshot from 2019-10-29 19-02-38](https://user-images.githubusercontent.com/16732393/67771712-d18cce00-fa7e-11e9-9d49-32ef85262175.png)
In `lbry-android/p4a/pythonforandroid/recipe.py`, `build_dir = glob.glob('build/lib.*')[0]` gives an empty list since there is no file path match in `pythonforandroid` directory. 

Are we looking to get this folder `lbry-android/.buildozer/android/platform/build/build/libs_collections`  through it?

**Comment by akinwale** [comment]
Done.
