### ISSUE TITLE
Use image publishes as thumbnail when publish is missing thumbnail

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#785]
https://github.com/lbryio/lbry-desktop/issues/3316

**Comment by kauffj** [comment]
@seanyesmunt completed this for desktop. Please consult his work on lbry-desktop and/or discuss with him if tackling this on mobile.

**Comment by seanyesmunt** [comment]
The solution I ended up with was this nasty file
https://github.com/lbryio/lbry-desktop/pull/3317/files#diff-738ea408af086ac2f52f2746d26a95a0

Here's where it's used: https://github.com/lbryio/lbry-desktop/pull/3317/files#diff-9242cd194ccb434fcf66eeb544e92b90R153

It's mostly weird because of the very different behavior on lbry.tv/desktop so it can definitely be simplified a bit.

**Comment by akinwale** [comment]
Done.
