### ISSUE TITLE
Re-vamp first run / first week of usage

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#796]
Many Android users download but fall off immediately. What can we do to get them more involved/hooked shortly after installing?

Ideas:

1. Claim email reward immediately and have them create channel ala lbry.tv
1. Encourage them more strongly to make a first publish
1. Encourage them to pick tags and subscribe to channels as part of first run (and let them earn rewards along the way!).
1. Focus on "first day" and "first week" set of notifications to help guide users through the process.

**Comment by akinwale** [comment]
Some thoughts I've had so far:
The original first run experience was designed around the idea of having to let the user be able to do something while the headers are being downloaded for the first time. Since this isn't the case anymore, and based on the experiences I've seen from other apps, there are a few things we could factor in to the new design, with a focus on removing as much friction as possible.

* Implement some form of hybrid mode where the app can make resolve and play requests using lbry.tv, while the sdk is starting up in the background. Once the sdk startup is complete, all sdk requests can be completed.
* Do not request for an email address until the user needs to make use of any feature that requires an account (the rewards and wallet sync drivers sort of already do this). This allows the user to start accessing content in the app immediately.
* A short guided process for selecting tags that the user may be interested in on first startup. The user can also choose to skip this step.
* Drop the request for the storage permission until a user makes their first download (there's already an issue for this).
